# Generated by Django 4.2.4 on 2023-08-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
