# Generated by Django 4.2.4 on 2023-08-20 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_profile_following_alter_profile_followers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
